name: CI

on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        python-version: ["3.10-dev", "3.9", "3.8", "3.7", "3.6"]
        os: [macos-latest, windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    env:
      IS_COVERAGE_ALLOWED: ${{ secrets.CODACY_PROJECT_TOKEN != '' }}
      IS_MASTER_BRANCH: ${{ github.ref == 'refs/heads/master' }}
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install pip dependencies
      run: pip install -r requirements-test.txt
    - name: Test
      run: pytest -v test.py
